nelmio_api_doc:
    documentation:
        info:
            title: FileFlow API
            description: Documentation page for AWESOME devs :D
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            #- ^/(?!api$) # Accepts routes under /api except /api/doc
            - ^/(?!(_error|api|History|_profiler|_wdt))
